apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  namespace: kryspin-redirect
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS redirects (
        id SERIAL PRIMARY KEY,
        path TEXT UNIQUE NOT NULL,
        redirect_to TEXT NOT NULL,
        last_update TIMESTAMPTZ,
        created_at TIMESTAMPTZ DEFAULT now(),
        hits INTEGER NOT NULL DEFAULT 0,
        last_hit TIMESTAMPTZ
    );
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: kryspin-redirect
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: postgres-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
        resources:
          requests:
            cpu: 25m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: initdb
        configMap:
          name: postgres-initdb
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: kryspin-redirect
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
